### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by meetxinzhang** [bioexcel/biobb#11]
**CODE**
from biobb_md.gromacs.pdb2gmx import Pdb2gmx

pdbCode = '7kkk'
fixed_pdb = '7kkk_fixed.pdb'

output_pdb2gmx_gro = pdbCode+'_pdb2gmx.gro'
output_pdb2gmx_top_zip = pdbCode+'_pdb2gmx_top.zip'

Pdb2gmx(input_pdb_path=fixed_pdb,
        output_gro_path=output_pdb2gmx_gro,
        output_top_zip_path=output_pdb2gmx_top_zip).launch()

**ERROR**
Traceback (most recent call last):
  File "/home/zhangxin/ACS/github/BioUtil/BioExcel/const_topol.py", line 24, in <module>
    output_top_zip_path=output_pdb2gmx_top_zip).launch()
  File "/home/zhangxin/anaconda3/envs/Biobb/lib/python3.7/site-packages/biobb_md/gromacs/pdb2gmx.py", line 45, in __init__
    self.gmx_version = get_gromacs_version(self.gmx_path)
  File "/home/zhangxin/anaconda3/envs/Biobb/lib/python3.7/site-packages/biobb_md/gromacs/common.py", line 29, in get_gromacs_version
    version = version_str.group(1).strip().replace(".", "")
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by adamhospital** [comment]
Can you update the version of the biobb_md that you are using? I think this problem was solved in the current version (v.3.5). New conda package here: https://anaconda.org/bioconda/biobb_md (v.3.5.1)
Also, it would help if you tell us how did you install the package. Are you using a conda installation?

**Comment by meetxinzhang** [comment]
> Can you update the version of the biobb_md that you are using? I think this problem was solved in the current version (v.3.5). New conda package here: https://anaconda.org/bioconda/biobb_md (v.3.5.1)
> Also, it would help if you tell us how did you install the package. Are you using a conda installation?

Hi,
I installed bio_md by:
  `conda install -c bioconda biobb_md`
3.5.1 actually.
I checked the source code of common.py: 

```
    unique_dir = fu.create_unique_dir()
    out_log, err_log = fu.get_logs(path=unique_dir, can_write_console=False)
    cmd = [gmx, "-version"]
    cmd_wrapper.CmdWrapper(cmd, out_log, err_log).launch()
    pattern = re.compile(r"GROMACS version:\s+(.+)")
    with open(os.path.join(unique_dir, 'log.out'), 'r') as log_file:
        for line in log_file:
            version_str = pattern.match(line.strip())
            if version_str:
                break
    print('debug:---------------', version_str)
    version = version_str.group(1).strip().replace(".", "")
```

and version_str=None,  so I modified code as follows at the last line:
```
# version = version_str.group(1).strip().replace(".", "")
version = '20204'
```
It works, but I get:
```
2021-02-04 09:27:47,303 [MainThread  ] [INFO ]  GROMACS Pdb2gmx 20204 version detected
2021-02-04 09:27:47,307 [MainThread  ] [INFO ]  gmx pdb2gmx -f 7kkk_fixed.pdb -o 7kkk_pdb2gmx.gro -p p2g.top -water spce -ff amber99sb-ildn -i p2g.itp

2021-02-04 09:27:47,308 [MainThread  ] [INFO ]  Exit code 127

2021-02-04 09:27:47,308 [MainThread  ] [INFO ]  /bin/bash: gmx: command not found

```
I can use the gmx command in the current anaconda environment in the terminal, so is there an environment variable that needs to be set?
ubuntu 20.04 LST
thanks

**Comment by adamhospital** [comment]
Thanks for the extended info. The first think I see is that the common.py that you are modifying is not the last version we have in the v.3.5.1. Take a look at the gitHub repo here https://github.com/bioexcel/biobb_md/blob/master/biobb_md/gromacs/common.py for the common.py and you will see that the lines you pasted have changed. 
Now we need to find why. 
It could be that you have different versions of biobb_md installed in your system. Could you please check that you are activating the corresponding conda environment where you installed the biobb_md v3.5 before running your script? Also, with the environment activated, could you please type `conda list` and paste the info here so that we can identify if the correct version of the biobb_md package is installed in this environment? 
Sometimes depending on the packages already installed in a conda environment, if you don't fix the version like this `conda install -c bioconda biobb_md==3.5.1`, an older version is automatically installed to avoid incompatible dependencies. `conda list` will tell us the version that was installed. 
If you want to test that, the easiest and quickest thing to do is to create a new, empty environment (preferably Python3.7), activate the new environment, and install the package with this command: `conda install -c bioconda biobb_md==3.5.1`
Hope it helps!

**Comment by meetxinzhang** [comment]
Your reply adressed the keypoint of this issue, as you said, the version of biobb_md is 0.1.2 when I run `conda list`

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
biobb_common              3.5.1                      py_0    bioconda
biobb_md                  0.1.2                      py_0    bioconda
biopython                 1.78             py37h7b6447c_0    defaults
```
then I run `conda install -c bioconda biobb_md==3.5.1`  as your suggustion, but i got:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
As you said, a new empty env, python=3.7. I don't kown why.
At last I sovled this problem by use `pip install "biobb_md>=3.5.1"`, now the biobb_md version=3.5.1. Anyway, thanks for your help, If you are interested in why `conda install -c bioconda biobb_md==3.5.1`  didn't works, I can keeps this issue open.
