### ISSUE TITLE
Installing library with GPU enabled gromacs

### ISSUE THREAD

**Issue by 91Abdullah** [bioexcel/biobb#21]
Hi, 

I just wanted to know if we can install the package with gpu enabled gromacs or amber while standalone gromacs installation is available with gpu I was just wondering if similar thing is available in this package too.

**Comment by adamhospital** [comment]
Dear Abdullah,

all the building blocks from the BioBB library have a common property called `binary_path`. This property can be defined by the user and pointed to a specific path containing the binary for the wrapped tool. This allows the use of local compilations, very important in HPC workflows, where the binaries specifically compiled for the supercomputer architecture are preferred, and where installation of tools are not always straightforward. As an example, the `binary_path` property can be pointed to a GPU-compatible version of GROMACS installed in the machine where the workflow is run, to use this compilation rather than the one available by default in the biobb_gromacs Conda package. 
Finally, if you are also interested in installing a GPU-compatible version of GROMACS from a Conda package, you can find them here: https://anaconda.org/conda-forge/gromacs/files (nompi_cuda)
The same methodology can be used for AMBER (and for the whole BioBB library and tools wrapped), although for AMBER the GPU-compatible PMEMD binary can not be found (afaik) as a standalone installation due to license requirements.

Hope it helps!

Regards,

-Adam-

**Comment by 91Abdullah** [comment]
Dear Adam,

Thank you for taking out time and guiding me in such an easy way. 

I think most preferred method for me would be installing GPU compatible gromacs from conda forge change. Since I need to run simulations for 10 ns and currently biobb package is redirecting all the computations towards CPU while GPU remains idle. 

Regards,
Abdullah
